from django.conf import settings

DEFAULT_ZARINPAL_CONFIGURATION = {
    'MECHANT_ID' : 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
    'WEBSERVICE' : 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',
    'DESCRIPTION' : 'ZARINPAL DJANGO OSCAR GATEWAY',
    'USE_SANDBOX' : True,
}

ZARINPAL_CONFIGURATION = getattr(settings , "ZARINPAL_CONFIGURATION" , DEFAULT_ZARINPAL_CONFIGURATION)

MMERCHANT_ID = ZARINPAL_CONFIGURATION.get("MECHANT_ID")
ZARINPAL_WEBSERVICE = ZARINPAL_CONFIGURATION.get("WEBSERVICE")
DESCRIPTION = ZARINPAL_CONFIGURATION.get("DESCRIPTION")



