# Generated by Django 3.2.12 on 2022-03-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zarrinpaytransaction',
            old_name='total_incl_tax',
            new_name='amount',
        ),
    ]
