# Generated by Django 3.2.12 on 2022-03-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_total_incl_tax_zarrinpaytransaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zarrinpaytransaction',
            old_name='amount',
            new_name='total_incl_tax',
        ),
    ]
