# Generated by Django 3.2.12 on 2022-03-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220305_2023'),
        ('checkout', '0008_auto_20220311_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarrinpaytransaction',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.shippingaddress'),
        ),
    ]
