# Generated by Django 3.2.12 on 2022-03-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_zarrinpaytransaction_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='shipping_method_class',
        ),
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='shipping_method_module',
        ),
    ]
