# Generated by Django 3.2.12 on 2022-03-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220305_2023'),
        ('checkout', '0013_auto_20220312_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarrinpaytransaction',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shippingaddress'),
        ),
    ]
