# Generated by Django 3.2.12 on 2022-03-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0010_auto_20220305_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarrinPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField()),
                ('total_incl_tax', models.PositiveBigIntegerField()),
                ('pay_type', models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('DEFERRED', 'DEFERRED'), ('AUTHENTICATE', 'AUTHENTICATE')], default='PAYMENT', max_length=15)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
            ],
        ),
    ]
