# Generated by Django 3.2.12 on 2022-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_amount_zarrinpaytransaction_total_incl_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zarrinpaytransaction',
            old_name='total_incl_tax',
            new_name='total_excl_tax',
        ),
        migrations.AlterField(
            model_name='zarrinpaytransaction',
            name='pay_type',
            field=models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('DEFERRED', 'DEFERRED'), ('AUTHENTICATE', 'AUTHENTICATE'), ('IN_TROUBLE_BUT_PAID', 'IN_TROUBLE_BUT_PAID')], default='PAYMENT', max_length=20),
        ),
    ]
