# Generated by Django 3.2.12 on 2022-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20220309_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarrinpaytransaction',
            name='pay_type',
            field=models.CharField(choices=[('PAYMENT', 'PANDING'), ('DEFERRED', 'DEFERRED'), ('AUTHENTICATE', 'AUTHENTICATE'), ('IN_TROUBLE_BUT_PAID', 'IN_TROUBLE_BUT_PAID')], default='PAYMENT', max_length=20),
        ),
    ]
