# Generated by Django 3.2.12 on 2022-03-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220305_2023'),
        ('checkout', '0006_auto_20220309_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='shipping_address_class',
        ),
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='shipping_address_module',
        ),
        migrations.AddField(
            model_name='zarrinpaytransaction',
            name='shipping_address',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='order.shippingaddress'),
            preserve_default=False,
        ),
    ]
