# Generated by Django 3.2.12 on 2022-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20220309_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='billing_address_class',
        ),
        migrations.RemoveField(
            model_name='zarrinpaytransaction',
            name='billing_address_module',
        ),
    ]
